---
name: Industrial CI
on:
    push:

jobs:
    ros_industrial_ci:
        name: ROS Industrial CI

        strategy:
            fail-fast: false
            matrix:
                ROS_DISTRO: [iron]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ros-industrial/industrial_ci@master
              env:
                  ROS_DISTRO: ${{matrix.ROS_DISTRO}}
